export const API_REDUCER_PATH = "api";

export enum RTKQueryTag {
  PROFILE = "PROFILE",
  CARDS = "CARDS",
  TRANSACTIONS = "TRANSACTIONS",
  WEEKLY_ACTIVITY = "WEEKLY_ACTIVITY",
  EXPENSE_STATS = "EXPENSE_STATS",
  CONTACTS = "CONTACTS",
  BALANCE_PROGRESSION = "BALANCE_PROGRESSION",
}
